name: Deploy bus
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      tenant_name: 'bus'
      server_ip: '198.37.120.210'
      ftp_username: 'bus@bus.srijaya.lk'
      server_dir: '/'
    secrets:
      ftp_password: ${{ secrets.FTP_PASS_BUS }}
